name: Snapshots
favicon: null
layout_spectrum: 0.72928
typography_spectrum: 0.34157967986539006
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141618'
    - '#445e70'
    - '#c6b7a6'
    - '#7a9299'
    - '#4f452f'
  brandStrength: 0.48484244104474783
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
