name: Snapshots
favicon: null
layout_spectrum: 0.04625181760638952
typography_spectrum: 0.34157967986539006
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.48484244104474783
  lightness: 0.4443325004540384
  saturation: 0.2069409405812621
  rhythmicContrast: 0.5329855750314891
purpose: []
